/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */


typedef volatile unsigned int vuint32_t;

#include <stdint.h>

#define RCC_BASE_ADDRESS     0x40021000
#define GPIOA_BASE_ADDRESS   0x40010800

#define RCC_APB2ENR     *((volatile uint32_t *)RCC_BASE_ADDRESS   + 0x18)
#define GPIOA_CRH       *((volatile uint32_t *)GPIOA_BASE_ADDRESS + 0x04)
#define GPIOA_ODR       *((volatile uint32_t *)GPIOA_BASE_ADDRESS + 0x0C)

typedef union {
	vuint32_t all_4byte;

	struct{
		vuint32_t resrved : 13;
		vuint32_t P_13  : 1;
	}Pin;
}Bit_Field;

/* Define pointer that point to stuct and hold the address of ODR Register */
volatile Bit_Field *ptr = (volatile Bit_Field *)(GPIOA_BASE_ADDRESS + 0x0C);

unsigned char Data_Section[3]   = {1,2,3};
unsigned char Rodata_Section[3] = {1,2,3};

int main(void)
{
	/* Enable RCC for GPIOA */
	RCC_APB2ENR |= 1<<2;
	/* clear bits from 20 : 24 => for GPIOA bin configuration */
	GPIOA_CRH &= 0xff0fffff;
	/* Set pin configuration */
	GPIOA_CRH |= 0x00200000;

	/* Toggle bin in infinite loop */
	while(1)
	{
		/* Set PA13 */
		//GPIOA_ODR |= 1<<13;

		ptr->Pin.P_13 = 1;

		/* busy delay */
		for (int i=0 ; i<5000 ; i++);

		/* Clear PA13 */
		//GPIOA_ODR &= ~(1<<13);

		ptr->Pin.P_13 = 0;
		
		/* busy delay */
		for (int i=0 ; i<5000 ; i++);
	}
}
